name: Daily Opening Price Update
on:
  schedule:
    # 9:20 AM IST (03:50 UTC)
    - cron: '50 3 * * 1-5'
    # 3:35 PM IST (10:05 UTC)
    - cron: '5 10 * * 1-5'

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
